services:
  mongodb:
    image: mongo:8
    container_name: mongodb
    ports:
      - "27017:27017" # Expose MongoDB on localhost for testing/debugging
    # environment:
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - app-network

  nodejs:
    image: node:22
    container_name: nodejs
    working_dir: /app
    volumes:
      - .:/app # Mount current directory to the /app directory in the container
    command: sh -c "npm install && npm run test-jest"
    environment:
      MONGO_HOST: "mongodb:27017"
      # MONGO_USER: root
      # MONGO_PASSWORD: example
    depends_on:
      - mongodb
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
