openapi: 3.0.0
info:
  title: Example API
  version: 1.0.0
paths: {}
components:
  schemas:
    Example:
      type: object
      required:
        - name
        - address
      properties:
        name:
          type: string
        age:
          type: integer
        address:
          type: object
          required:
            - street
          properties:
            street:
              type: string
            city:
              type: string
