name: Aggregation tests

on:
  push:
    paths:
      - 'aggregation/**'

## https://github.com/supercharge/mongodb-github-action/blob/master/.github/workflows/test-single-instance.yml
## https://github.com/supercharge/mongodb-github-action

jobs:
  mongodb-action:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mongodb-version: [4.2]

    name: Start MongoDB Server v${{ matrix.mongodb-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Start MongoDB Server
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - run: npm install
        env:
          CI: true

      - run: npm test .aggregation/test/setup.js
        env:
          CI: true